### ISSUE TITLE
Compability with other libraries using Client functionality

### ISSUE THREAD

**Issue by nmaas87** [Wiznet/WizFi360_arduino_library#2]
It looks like this Arduino library is not completely on par in terms of compability with other Arduino libraries exposing or using network client mode. For example, I could not get https://github.com/256dpi/arduino-mqtt working with it. Connecting to wifi still works, but it is not able to connect via mqtt to the servers.
Could you take a look?
Thank you

**Comment by Giung951** [comment]
Hi @nmaas87

I'm sorry for the late reply.

This Arduino Library is not fully compatible with other Arduino libraries.

Therefore, if there are necessary parts other than those supported by this Arduino library, this library should be modified or additionally implemented.

Are you trying to use 'https://github.com/256dpi/arduino-mqtt'?

**Comment by nmaas87** [comment]
Hi @GiungKim , yes that is correct. 
But it did not work. Could you take a look?
Thanks

**Comment by Giung951** [comment]
Hi @nmaas87

Let me check the MQTT arduino library.

**Comment by nmaas87** [comment]
Anything new @GiungKim ?

**Comment by Giung951** [comment]
Hi @nmaas87

 I checked the MQTT library of 'https://github.com/256dpi/arduino-mqtt', when used with the WizFi360 Arduino library, it does not work like the problem mentioned before.

It will need to be modified and further implemented to synchronize the WizFi360 Arduino library with the MQTT library.

**Comment by nmaas87** [comment]
Hi @GiungKim 
thanks! Do you know about any library under Arduino that is compatible with WizFi360 and MQTT?
The mentioned library was able to work in the past with the W5100S-EVB-Pico and a lot of different other platforms, so it looks like the WizFi360 library is not developed to the standards of a Arduino "net" library. With that, probably a lot of other librarys also don't work, which limits the usability of the WizFi360 severely. As the WizFi360 is now more than 3 years old and still is not able to integrate into the basic Arduino "net" ecosystem I really need to ask: Will it ever be corrected and usable? Or does Wiznet do not wish to support Arduino? (which could also be a valid case, but then it should not market it towards Arduino). The question is especially as - if I had no sent my PR to the other repo ( https://github.com/ekkai/WizFi360/issues/1 ) - whose contents you did integrate into this repo without even credinting me ( https://github.com/Wiznet/WizFi360_arduino_library/commit/4f37ddb9c4acbd7efad4e18f25e81ca7206891d1#diff-3514a6b9e2d9db12514c6ec5aa883f329f3a746163316a61545cc316a0e24c76 ) - this library would not been able to be compiled at all and be used, so basically dead, which points more towards Wiznet does not strive for Arduino compability.

Please do not take this personally, its just that I am really asking myself why a (not even half finished) product is now pushed towards to the community in hopes that they might fix it.

Thanks for your help!
