### ISSUE TITLE
WizFi360Drv::getIpAddress(IPAddress& ip) gets hung 

### ISSUE THREAD

**Issue by ralphjy** [Wiznet/WizFi360_arduino_library#4]
I am trying the example WebServerLed and the function being used to get the IP addr gets hung and doesn't return.  It appears that I get connected okay because I can comment out the code in printWiFiStatus() and the example will work (except for printing out the ipAddr.  I have talked with another person using a different example and having precisely the same issue.

We are both using the WIZFI360_EVB_PICO board.

**Comment by ralphjy** [comment]
Not sure if anyone is still supporting this library, but I thought that I would mention that this issue is associated with the version of the RP2040 board library provided by Earle Philhower.  The function works with version 2.2.2, but hangs when using a newer board library version like 2.4.0 or 2.5.0.  - don't know why.

**Comment by Giung951** [comment]
Hello @ralphjy

We checked the issue that you told us about, and fixed the issue and created it as a branch.

- https://github.com/Wiznet/WizFi360_arduino_library/tree/WizFi360-EVB-Pico
