### ISSUE TITLE
cannot connect WizFi360-EVB-Pico

### ISSUE THREAD

**Issue by mhanuel26** [Wiznet/WizFi360_arduino_library#5]
Hi, 

I am testing the library and always get the following,

```
[WizFi360] >>> TIMEOUT >>>
[WizFi360] >>> TIMEOUT >>>
[WizFi360] >>> TIMEOUT >>>
[WizFi360] >>> TIMEOUT >>>
[WizFi360] >>> TIMEOUT >>>
[WizFi360] Cannot initialize WizFi360 module
[WizFi360] >>> TIMEOUT >>>
[WizFi360] No tag found
WiFi shield not present
```

I have change define to 

`#define WIZFI360_EVB_PICO`

I also noticed the original code has defined the RX and TX pins on 6 and 7, but the [hardware](https://docs.wiznet.io/Product/Open-Source-Hardware/wizfi360-evb-pico)  seems to have pins 4 and 5 for that. So I also change the pins to 4 and 5. Same issue.

Now I am seeing there are CTS and RTS lines, I am wondering if the lines are ins a state that prevents the WizFi360 to send/receive data.

Any thoughts?

**Comment by vishnumaiea** [comment]
Are you sure you have initialized the correct UART that is connected to the WizFi360 module? On the WizFi360-EVB-Pico, the Wi-Fi module is connected to Serial2 and you need to initialize it with the default baudrate of 115200. This is done something like below,

```
Serial.begin(SERIAL_BAUDRATE);  //USB serial
Serial2.begin(SERIAL2_BAUDRATE); //WizFi serial

WiFi.init(&Serial2);

// check for the presence of the module
if (WiFi.status() == WL_NO_SHIELD) {
  Serial.println("WiFi module is not present");
  // don't continue
  while (true);
}
```

**Comment by mhanuel26** [comment]
Hi,

You are saying if I understand correctly that the original code

```
#elif defined(WIZFI360_EVB_PICO)
SoftwareSerial Serial2(6, 7); // RX, TX
#endif
```

Is not working for pico and you need to actually use the hardware serial right? In this case replace the software serial with the hardware serial init?

Thanks,
Manuel

**Comment by mhanuel26** [comment]
Hi,

For the record,

The issue was the definition of pins for TX and RX which I was wrong selecting the generic version of RP2040 pins.

Thanks,
