### ISSUE TITLE
MQTT branch working?

### ISSUE THREAD

**Issue by ralphjy** [Wiznet/WizFi360_arduino_library#6]
I can't get the MQTT example to work on a WizFi360-EVB-Pico.  I know this is a new branch to the repo.  Has it been tested and known to be working?

**Comment by Giung951** [comment]
Hello @ralphjy

I checked that the MQTT example of mqtt branch is working.

However, since it is still in an unstable state, it may not work normally, and it has not been added to the main branch.

Please refer to this.
